### ISSUE TITLE
Problem with class field initialization, Swing UI Designer

### ISSUE THREAD

**Issue by i582** [JetBrains/gradle-intellij-plugin#966]
I have quite a lot of forms in my plugin made using Swing UI Designer. 
In 2021.3 with plugin version 1.3.0 everything worked well, but when I updated the version to 2022.1 and the plugin to version 1.5.3, exceptions appeared.

After the update, when trying to create a window, an exception appears that the `lateinit` class property has not been initialized. For nullable properties, the value has always become `null`. For the form used on the plugin settings page, this resulted in an endless loading.

The corresponding classes for forms are written in Kotlin.

After I changed the plugin version to 1.5.2 everything started working again.

**Comment by hsz** [comment]
@i582 Issue is fixed, but I'd like to double-check it with your setup. Could you please provide a minimal-reproducible project so I could test it locally?

**Comment by fffguo** [comment]
I encountered the same problem

**Comment by hsz** [comment]
I've released a snapshot version – could you please verify if it resolved this issue?

https://github.com/JetBrains/gradle-intellij-plugin#snapshot-version

**Comment by fffguo** [comment]
Wait, let me try

**Comment by fffguo** [comment]
> I've released a snapshot version – could you please verify if it resolved this issue?
> 
> https://github.com/JetBrains/gradle-intellij-plugin#snapshot-version

Unfortunately, 1.6.0-SNAPSHOT did not solve the problem
![image](https://user-images.githubusercontent.com/27751972/168269276-78d38d1d-3acc-4185-bdff-8f06aea48348.png)

**Comment by fffguo** [comment]
**You can refer to the branch code:** 
https://github.com/fffguo/qianmi-idea-plugin/tree/1.6.0-SNAPSHOT
- The code environment is ready
- Focus on observation of this class：com.github.qianmi.ui.setting.PluginSettingPage
- setting -> other setting -> 千米网: This operation can reproduce

**Comment by hsz** [comment]
@fffguo Could you, please provide sources or at least a minimal reproducible example so I could check it locally?
We're heading the release, so it'd be great to include the fix for this issue.

**Comment by hsz** [comment]
Thank you for providing sources. I was able to spot the actual issue – instrumentation was working properly, but generated files weren't included in the output jar artifact.
Everything now works as expected – I've also updated the `1.6.0-SNAPSHOT` release so the fix is available there.
Could you please verify if it works for you?

**Comment by fffguo** [comment]
I tried again，`1.6.0-SNAPSHOT` can  solve this problem.
Thank you for your repair @hsz

**Comment by hsz** [comment]
Thank you for the confirmation!

**Comment by Ariel5yang** [comment]
there are many page made using swing ui designer  in my plugin, In 2023.1 with plugin version 1.10.0 gralde 7.2 everything worked well,then i upgade the plugin version to 1.15.0, and upgrade the gradle to 8.2.1，then the form defined fields is null
